name: Mildly interesting facts
  uses: lowlighter/metrics@latest
  with:
    filename: habits.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_habits: yes
    plugin_habits_facts: yes
    plugin_habits_charts: no
    config_timezone: Asia/Kuala_Lumpur

