name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
          plugin_people: yes
          plugin_people_types: followers
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, deployer, member, maintainer, developer, scripter
          plugin_achievements_threshold: X
          plugin_languages_ignored: >-
            html, css, dockerfile, makefile, qmake, cmake
          config_timezone: Asia/Kuala_Lumpur
          
